environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py34
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38
  - TOXENV: py39

build: off

install:
- pip install tox

test_script:
- tox
